services:

  mysql-server:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3306:3306
    container_name: mysql-server
    volumes:
      - ./mysql_data:/var/lib/mysql

  mysql-test:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: test135
      MYSQL_DATABASE: zupzup_test_db
    ports:
      - 3307:3306
    container_name: mysql-test
