version: '3.8'

services:
  web-blue:
    image: sejongzupzup/api-server:latest
    container_name: web-blue
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: always
    volumes:
      - /home/ubuntu/zupzup/logs:/app/logs

  web-green:
    image: sejongzupzup/api-server:latest
    container_name: web-green
    ports:
      - "8081:8080"
    env_file:
      - ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: always
    volumes:
      - /home/ubuntu/zupzup/logs:/app/logs
