spring:

  datasource:
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate

cors:
  allowed-origins: "https://sejong-zupzup.kr, https://www.sejong-zupzup.kr, https://api.sejong-zupzup.kr"

jwt:
  cookie:
    domain: .sejong-zupzup.kr
    secure: true
    samesite: Lax

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
