name: zupzup CI/CD with GitHub Actions

on:
  push:
    branches:
      - chxghee/chore-38-reset

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    # í…ŒìŠ¤íŠ¸ìš© Mysql DB ì»¨í…Œì´ë„ˆ ìƒì„±
    services:
      mysql-test-db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: test135
          MYSQL_DATABASE: zupzup_test_db
        ports:
          - 3307:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: ğŸ—‚ ë ˆí¬ì§€í† ë¦¬ì—ì„œ í”„ë¡œì íŠ¸ íŒŒì¼ ê°€ì ¸ì˜¤ê¸°...
        uses: actions/checkout@v4

      - name: â˜•ï¸ github-actions JDK 21 ì„¤ì •...
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: âš™ï¸ Gradle ì„¤ì •...
        uses: gradle/actions/setup-gradle@v3

      - name: âœï¸ ì‹¤í–‰ ê¶Œí•œ ë¶€ì—¬...
        run: chmod +x gradlew

      - name: ğŸ› ï¸ í…ŒìŠ¤íŠ¸ ë° ë¹Œë“œ...
        run: ./gradlew clean build

      - name: ğŸ³ Docker Hub ë¡œê·¸ì¸...
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: ğŸ“¦ Docker ì´ë¯¸ì§€ ë¹Œë“œ ë° í‘¸ì‹œ...
        run: |
          docker build -t sejongzupzup/api-server:latest .
          docker push sejongzupzup/api-server:latest

      - name: ğŸ’¾ EC2ì— ë°°í¬ ê´€ë ¨ íŒŒì¼ ì „ì†¡...
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose-prod.yml,script/deploy.sh"
          target: "/home/ubuntu/zupzup"
          overwrite: true

      - name: ğŸš€ EC2ì—ì„œ ë°°í¬ ìŠ¤í¬ë¦½íŠ¸ íŒŒì¼ ì‹¤í–‰...
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cat << EOF > /home/ubuntu/zupzup/.env
            DB_HOST=${{ secrets.DB_HOST }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            AWS_S3_ACCESS_KEY=${{ secrets.AWS_S3_ACCESS_KEY }}
            AWS_S3_SECRET_ACCESS_KEY=${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
            AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}
            ACCESS_TOKEN_SECRET_KEY=${{ secrets.ACCESS_TOKEN_SECRET_KEY }}
            ACCESS_TOKEN_EXPIRATION=${{ secrets.ACCESS_TOKEN_EXPIRATION }}
            STUDENT_VERIFICATION_SESSION_TIME=${{ secrets.STUDENT_VERIFICATION_SESSION_TIME }}
            EOF
            
            chmod +x /home/ubuntu/zupzup/script/deploy.sh
            
            /home/ubuntu/zupzup/script/deploy.sh
            
